apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: message-classifier-rollout
  namespace: message-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      run: message-classifier
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: "35s"}
      - setWeight: 50
      - pause: {duration: "35s"}
      - setWeight: 80
      - pause: {duration: "35s"}
  template:
    metadata:
      labels:
        run: message-classifier
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-group-type
                operator: In
                values:
                - message-classifier
      containers:
      - name: message-classifier
        image: lsjpjs1/message-classifier:65
        command: ["/bin/sh", "-c", "java -verbose:gc -Xms1200m -Xmx1200m -XX:+PrintGC -XX:+PrintCommandLineFlags -XX:NativeMemoryTracking=detail -jar ./message-classifier.jar"]
        resources:
          requests:
            memory: "1000Mi"
