---

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: chat-core-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      run: chat-core
  template:
    metadata:
      labels:
        run: chat-core
    spec:
      containers:
      - name: chat-core
        image: lsjpjs1/chat:64
        command: ["/bin/sh", "-c", "WAS_ID=$(echo $HOSTNAME | grep -o '[0-9]*$'); java -verbose:gc -Xms1200m -Xmx1200m -XX:+PrintGC -XX:+PrintCommandLineFlags -XX:NativeMemoryTracking=detail -Dwas.id=${WAS_ID} -jar ./chat.jar"]
        resources:
          requests:
            memory: "1000Mi"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: "15s"}
      - setWeight: 50
      - pause: {duration: "15s"}
      - setWeight: 100
      analysis:
        templates:
        - templateName: failed-request-rate
        args:
        - name: service-name
          value: chat-core-service

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: failed-request-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: failed-requests
    interval: 15s
    failureLimit: 1
    provider:
      prometheus:
        query: |
          sum(rate(http_requests_total{job="{{args.service-name}}",status=~"5.*"}[2m]))
          /
          sum(rate(http_requests_total{job="{{args.service-name}}"}[2m]))