apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-classifier-deployment
  namespace: message-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      run: message-classifier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        run: message-classifier
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-group-type
                operator: In
                values:
                - message-classifier
      containers:
        - name: message-classifier
          image: lsjpjs1/message-classifier:9
          command: ["/bin/sh", "-c", "java -verbose:gc -Xms1200m -Xmx1200m -XX:+PrintGC -XX:+PrintCommandLineFlags -XX:NativeMemoryTracking=detail -jar ./message-classifier.jar"]
          resources:
            requests:
              memory: "1000Mi"
